language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-reactor' ]; then cd .. && eval "mv $currentfolder generator-reactor" && cd generator-reactor; fi
